pixiv     = "https://www.pixiv.net/en/users/129876664"
x         = "https://x.com/peerawatm_"
instagram = "https://www.instagram.com/peerawatm_/"
tiktok    = "https://www.tiktok.com/@peerawatm_"
youtube   = "https://www.youtube.com/@peerawatm"
